remote_theme: just-the-docs/just-the-docs

title: SYSU-ARCH 
description: Welcome to SYSU-ARCH's homepage

logo: "/assets/images/ARSYSU.png"

callouts_level: quiet
callouts:
  highlight:
    color: green
  question:
    color: red
  outline:
    color: yellow

footer_content: "Supported by <a href=\"https://gty111.github.io\">TianYu GUO</a> and proofreaded by YuHao GU"

color_scheme: light
